### ISSUE TITLE
Change sensor pull-up value to match TFPROBE01

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFRPM01#10]
Změnit hodnotu pull-upu na vstupu signálu u TFRPM01, tak aby bylo možné TFRPM používat přimo s [TFPROBE01](https://github.com/ThunderFly-aerospace/TFPROBE01)

**Comment by ChroustJan** [comment]
Aktuálně se testuje 10k

**Comment by kaklik** [comment]
S hodnotou 10k byl při použití v kombinaci [se snímacím bubínkem](https://github.com/ThunderFly-aerospace/TF-G2/issues/64#issuecomment-761890227) pozorován problém, kdy na přímém slunečním světle přestalo fungovat čítání snímače. 

Současně existuje předpoklad, že je to způsobeno především prosvícením bubínku slunečním světlem. Je nutné tento problém dále analyzovat. Může však dojít k nutnosti snížit hodnotu pull-upu, aby byla snížena citlivost senzoru.

**Comment by ChroustJan** [comment]
Zkusíte tohle nějak analyzovat? Bylo by dobré znát hodnoty do nové várky osazování. A pokud není chtělo by to popsat do návodu, že při použití této technologie může být potřeba doladit hodnoty. Podle zvolené mezery a odrazného materiálu.

**Comment by kaklik** [comment]
Tak z aktuálních poznatků vyplývá, že testovaná hodnota pull-upu 4k7 je minimálně pro použití na TF-G2 příliš nízká. Kromě jiného se ukázala i značná citlivost na barvu materiálu. Viz následdující grafy: 

Fialová odrazná plocha
![TFPROBE_Purple](https://user-images.githubusercontent.com/1194177/108642581-656d7f00-74a6-11eb-81bf-d083080d595b.png)

Modrá odrazná plocha
![TFPROBE_blue](https://user-images.githubusercontent.com/1194177/108642583-68686f80-74a6-11eb-906a-fb2a9b2dd74b.png)

Šedá odrazná plocha
![TFPROBE_gray](https://user-images.githubusercontent.com/1194177/108642587-6d2d2380-74a6-11eb-9c20-0eab934c27e3.png)

V žádném z těchto případů nedocházelo ke spínání vstupu TFRPM a kombinaci pull-up/materiál nelze použít. Při použití rezistoru 10k2 je situace poněkud lepší: 

Fialová
![TFRPM_purple](https://user-images.githubusercontent.com/1194177/108643911-e760a680-74ac-11eb-8945-8b3edbc81333.png)

Modrá
![TFRPM_blue](https://user-images.githubusercontent.com/1194177/108643922-f47d9580-74ac-11eb-9d55-aa3a0722e9ef.png)

Šedá
![TFRPM_gray](https://user-images.githubusercontent.com/1194177/108643925-fc3d3a00-74ac-11eb-9e39-1821ab783825.png)

Nicméně i z těchto hodnot je vidět, že napěťové úrovně spínání jsou i v tomto případě relativně hraniční. Pull-up by tak zřejmě měl být ještě o něco větší. Zítra zkusím vytisknout rolničiky i v jiných barvách. Neboť je zjevné, že z viditelných barev nelze usuzovat na chování barvy v infračerveném spektru.

**Comment by kaklik** [comment]
Tady jsou nové obrázky po následujících změnách:

- zvětšení proudu IR LED na 20 mA zmenšením rezistoru R1 (TFPROBE) ze 180 na 82 Ohm
- Instalace 10k pull-upu na TFRPM input z TFPROBE

Fialová
![Newfile1](https://user-images.githubusercontent.com/1194177/108878963-0c662e00-7601-11eb-8e0c-6984cedc14af.png)
Modrá
![Newfile2](https://user-images.githubusercontent.com/1194177/108878984-138d3c00-7601-11eb-9027-1240019d80a0.png)
Šedá
![Newfile3](https://user-images.githubusercontent.com/1194177/108878995-15ef9600-7601-11eb-80a7-5d74e3490dea.png)

**Comment by kaklik** [comment]
Navrhoval bych  pull-up R1 zkusit používat 22k.   Omezení proudu rezistorem R2 omezit hodnotou 82 Ohm. 
Upravit je potřeba i [nastavení hodnot na TFPROBE viz samostatné issue](https://github.com/ThunderFly-aerospace/TFPROBE01/issues/5). 

Po těchto úpravách vypadají signály pro fialový a zelený bubínek relativně použitelně.  Systém je ale hodně citlivý na vzdálenost možná zde bude muset dojít ještě k mírným konstrukčním úpravám. 

Fialový bubínek: 
![Newfile9](https://user-images.githubusercontent.com/1194177/109979210-efb3af80-7cfe-11eb-9fa7-cdc67a0ba5d8.png)

Zelený bubínek ve stejné vzdálenosti jako fialový: 
![Newfile10](https://user-images.githubusercontent.com/1194177/109979131-d7dc2b80-7cfe-11eb-815e-4d886820bc1f.png)



Zelený bubínek při kratší vzdálenosti: 
![Newfile11](https://user-images.githubusercontent.com/1194177/109979066-c561f200-7cfe-11eb-9a40-fc500cb814dc.png)



Šedivý bubínek je ale stále nepoužitelný:

![Newfile12](https://user-images.githubusercontent.com/1194177/109978927-a7948d00-7cfe-11eb-8297-7d3f91d1442a.png)

**Comment by ChroustJan** [comment]
Osazeno R1 22K a R2 82R

**Comment by kaklik** [comment]
S nezměněnou konfigurací oproti předchozímu komentáři jsem vyzkoušel bubínek vytištěný z barvy "Teal".

![TFRPM_teal](https://user-images.githubusercontent.com/1194177/111805098-064a3100-88d1-11eb-854e-32610b9d0e71.png)

Zatím to vypadá, že zhlediska snímání je to nejvhodnější barva. 

![image](https://user-images.githubusercontent.com/1194177/111808484-57a7ef80-88d4-11eb-95ad-c5ddb96ca756.png)

**Comment by kaklik** [comment]
Po úpravě  TFPROBE podle https://github.com/ThunderFly-aerospace/TFPROBE01/issues/5

A při zachování konfigurace TFRPM https://github.com/ThunderFly-aerospace/TFRPM01/issues/10#issuecomment-798528538 , jsem zkoušel změřit napěťový průběh na vstupu TFRPM ze sondy TFPROBE. 

### Fialový  klobouček

![Purple plastics](https://user-images.githubusercontent.com/1194177/111905469-19354080-8a4c-11eb-902a-06b2d4bb853c.png)

### Teal  klobouček

![Newfile16](https://user-images.githubusercontent.com/1194177/111905486-2f430100-8a4c-11eb-92a5-dbe1b72d509b.png)

Jak je z grafů vidět, tak hodnota minimálního i maximálního napětí klesla. S tím že maximální napětí je nyní pod hranicí 2V, což neodpovídá vstupním napěťovým úrovním #16 .   Důsledkem toho, je že u barvy Teal je TFRPM senzor část úvratě v "sepnutém stavu" s rozsvícenou LED a nečítá pulzy. 

Z testovaných barev  (Šedá, modrá, fialová, Teal, Bílá, Zelená), je teď optimální kotouček vytištěný ze zelené barvy, který funguje spolehlivě. 

![Green cylinder](https://user-images.githubusercontent.com/1194177/111905966-a37ea400-8a4e-11eb-82ef-669352e1b8cb.png)

**Comment by kaklik** [comment]
Jinak bez kloboučku je na tom výstupu TFPROBE  cca 3V. Což znamená, že v té horní mezi je ještě celkem dost velká rezerva, která zaniká tím že ten senzor je částečně osvětlený odraženým světlem z vnitřku kloboučku. 

Pokud by zevnitř bylo něco, co to světlo lépe pohltí, než prázdný prostor, tak by se zřejmě dala snížit ta citlivost na barvu.

**Comment by kaklik** [comment]
Záležitost byla nakonec vyřešena přebarvením zubů klobočku viz komentář: https://github.com/ThunderFly-aerospace/TF-G2/issues/64#issuecomment-808915707

Toto přebarvení zřejmě dále umožňuje případně snížit hodnotu pull-upu na TFRPM.
