### ISSUE TITLE
označení R1 - pullup Signalu

### ISSUE THREAD

**Issue by slimonslimon** [ThunderFly-aerospace/TFRPM01#12]
rezostor R1 by mohl být označený nějak na plošném spoji, když dokumentace odkazuje na jeho případné nahrazení.

**Comment by kaklik** [comment]
Tohle řeší objednání potisku i na stranu součástek. @ChroustJan  rezitory v potisku označil takto: 

![image](https://user-images.githubusercontent.com/1194177/108359067-ccadd980-71ef-11eb-9c99-f321581b5da2.png)
