### ISSUE TITLE
Návrh samolepky

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFRPM01#14]
Obsah:
QR kód - buď na thunderfly.cz nebo na repozitář

Zvážit možnost vytvoření dvojice samolepek pro spodní stranu. Jedna se zaškrtnutím adresy 0x51 a druhou s 0x50.

**Comment by kaklik** [comment]
I²C Adresa na spodní (montážní) straně je celkem k ničemu.  Protože to vyžaduje modul nejdříve vymontovat, aby na něj bylo vidět.

**Comment by ChroustJan** [comment]
Výsledný návrh samolepky:
![image](https://user-images.githubusercontent.com/9783606/111035741-115a1880-841c-11eb-9869-baa206125fbd.png)

**Comment by roman-dvorak** [comment]
Mohl by mi prosím někdo (@kaklik  nebo @ChroustJan ) změřit velikost toho archu (nebo říct, co je to za formát), na kterém jsou vytištěné samolepky?

**Comment by kaklik** [comment]
> Mohl by mi prosím někdo (@kaklik nebo @ChroustJan ) změřit velikost toho archu (nebo říct, co je to za formát), na kterém jsou vytištěné samolepky?

Ten arch je 303x240mm ale jestli je to pevný formát, to nevím. Okraje vypadají že jsou něčím dodatečně střihané. Na rubové straně je logo téhle firmy: https://www.arlon.com/na_en/
