### ISSUE TITLE
Proražená dioda D1

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#15]
Na jednom z modulů došlo během relativně běžného používání k proražení zenerovo diody D1.  Hlavní anomálií byla nízká teplota (okolo -12 °C).

![image](https://user-images.githubusercontent.com/1194177/108570840-15a87f80-730f-11eb-8882-ecef2781a421.png)

Lze předpokládat, že dioda odešla v důsledku otevření na vyšším napětí s následným nadproudem, který diodu zničil. 
Podle schéma je tam neznámý typ diody s otevíracím napětím 5.6V To je však velmi blízko změřenému napájecímu napětí 5.4 V při napájení z akumulátoru přes CUAV power modul. 
Vzhledem k absenci přesného označení typu diody ve schéma, nelze určit jaká je její teplotní charakteristika a zda na této události mohla mít podíl nízká teplota během provozu.

**Comment by ChroustJan** [comment]
@kaklik  BZV55C-5,6V

**Comment by kaklik** [comment]
K tomuto problému bylo vytvořeno [issue v oficiální dokumentaci Pixhawk.](https://github.com/pixhawk/Pixhawk-Standards/issues/15#issuecomment-786302167)
Zůstává však bez relevantního řešení.

**Comment by kaklik** [comment]
Issue v dokumentaci stále zůstává bez odpovědi. Navrhuji problém zkusit vyřešit použitím typu zenerovo diody s vyšším otevíracím napětím: BZV55C 6.2BSA

**Comment by ChroustJan** [comment]
@kaklik  myslíš prostě BZV55C6V2 ? Nenašel jsem co znamená BSA

**Comment by kaklik** [comment]
> @kaklik myslíš prostě BZV55C6V2 ? Nenašel jsem co znamená BSA

BSA specifikuje možný rozptyl otevíracího napětí. Viz datasheet například zde: https://www.rectron.com/data_sheets/bzv55c-bs.pdf

**Comment by ChroustJan** [comment]
Parametr je to hezký, ale našel jsi místo, kde to jde koupit?

Máme tuto: https://www.tme.eu/cz/details/bzv55c6v2/zenerovy-diody-smd/dc-components/

**Comment by ChroustJan** [comment]
Dán tento typ:  https://www.tme.eu/cz/details/bzv55c6v2/zenerovy-diody-smd/dc-components/
