### ISSUE TITLE
Zatížení 74HC1G14GW proudem z LED 

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#17]
Při řešení  #16 jsem zjistil, že v [datasheetu](https://www.ti.com/lit/ds/symlink/sn74hc14.pdf?ts=1613907697872) se zmiňují o: 
"Recommended output conditions: –  Load currents should not exceed 4 mA per output"

Přibližným odhadem (3,3−1,7)÷180  jsem ale zjistil, že proud skrz LED je nyní zřejmě něco jako  0,0089A. Což zřejmě nesplňuje tento požadavek. 

Je tak na zvážení, zda není vhodné použít jiný typ této součástky.

**Comment by ChroustJan** [comment]
@kaklik zkusil by jsi prosím co nejdříve najít vhodnou náhradu?

**Comment by kaklik** [comment]
> @kaklik zkusil by jsi prosím co nejdříve najít vhodnou náhradu?

Pracuju na tom. Domnívám se ale, že by bylo zároveň vhodné zjistit, jak moc se sníží jas indikační LED v případě, že se dodrží výše uvedené kritérium zátěže výstupu.

**Comment by kaklik** [comment]
Asi bych navrhoval začít používat tohle: [SN74LVC1G14-Q1](https://www.ti.com/lit/ds/symlink/sn74lvc1g14-q1.pdf?ts=1614074438985&ref_url=https%253A%252F%252Fwww.ti.com%252Fsitesearch%252Fdocs%252Funiversalsearch.tsp%253FsearchTerm%253Dsingle%2Bschmitt%2Btrigger%2Binverter)

Je to sice hůře dostupné a mírně dražší, ale není to takový mizerný řešení, jako ten předchozí typ.  Výstup to má +/- 24 mA. 
Tohle je navíc kvalifikovaný pro automotive a má to vysokou ESD odolnost.

**Comment by ChroustJan** [comment]
Vypadá to dobře. Pokud by se chtělo šetřit, tak je ke zvážení verze bez Q1. Ale myslím si, že příplatek 1kč si můžeme dovolit.

**Comment by ChroustJan** [comment]
V novém osazování použito IO: SN74LVC1G14-Q1

**Comment by kaklik** [comment]
Změřil jsem napěťové úrovně na  výstupu IO U2A a na LED.

### Průběh napětí na výstupu IO

![U2A output](https://user-images.githubusercontent.com/1194177/111903319-061d7300-8a42-11eb-952d-80446f4b5cf9.png)


### Průběh napětí na LED D2 

![Red LED voltage](https://user-images.githubusercontent.com/1194177/111903323-0a499080-8a42-11eb-9711-1d03074217b5.png)

Z obou průběhů je vidět, že úbytek na rezistoru R4 s hodnotou 51 Ohm, je 1,05 V.  LED tak protéká 20,5 mA. 
Zároveň výstupní úrovně z U2A jsou bezpečně v požadovaném vstupním prozsahu IO U1, který je 0,7*3,3=2,31V  a spodní úroveň 0,3*3,3=0,99V.

Úprava je proto funkční.
