### ISSUE TITLE
Zkosit hranu otvoru pro hlavu šroubu

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#18]
Samolepku technicky není možné na krabičku nalepit úplně přesně.  Je tak vidět okraj otvoru pro hlavu šroubu, který je díky tisku nepřesný. 

![image](https://user-images.githubusercontent.com/1194177/111664633-41d1f600-8812-11eb-9c84-4de483531de6.png)

Situaci by zřejmě mohlo vyřešit malé zkosení hrany otvoru, tak aby nepřesná hrana byla schována pod samolepkou.   Otvor zřejmě stačí zkosit o 45 stupňů ve výšce třeba 5ti vrstev (Aktuálně předpokládaná tisková vrstva je 0.1mm). Tím bude model mít mírně větší návrhový otvor než samolepka.  Při tisku na podložku se ale hrana otvoru mírně rozplácne, takže se rozdíl průměrů vyrovná.

**Comment by ChroustJan** [comment]
Buď to neřešit, nebo úprava krabičky.

**Comment by kaklik** [comment]
I přes to, že se mi samolepku tentokrát na krabičku nepodařilo nalepit tak přesně, tak úprava krabičky je výrazné zlepšení. 

![image](https://user-images.githubusercontent.com/1194177/111874620-55a66500-8996-11eb-8f00-8b43fa010b4f.png)
