### ISSUE TITLE
Svítivost LED pod samolepkou

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#20]
Aktuální samolepka je natištěna na bílé PVC fólii.  Indikační LED skrz fólii nesvítí příliš zřetelně:

![image](https://user-images.githubusercontent.com/1194177/111668361-f6b9e200-8815-11eb-9c73-ad79c49041a3.png)

Na samolepce je navíc vidět, že nesvítí celá bílá plocha vlivem posunutí samolepky při lepení na krabičku.  Tmavá plocha okolo puntíku ale naopak prosvětlená není, čemuž pomáhá černý lem okolo bílého puntíku. 

Možná řešení
-  [x] Zvětšit proud LED, aby bylo dosaženo maximální svítivosti  #17 
-  [x] Zvětšit otvor pod samolepkou nad průměr puntíku na samolepce -  tím bude navíc zvětšena tolerance k nepřesnému lepení
-  [x] Otvor směrem k LED udělat kónický s průměrem mírně větším, než je průměr otvoru PCB pro LED
-  [x] Ztenčit víčko, aby LED byla blíže samolepce
-  [x] Samolepku objednat na průhledné fólii

**Comment by ChroustJan** [comment]
Za mě to buď neřešit, nebo udělat úpravu krabičky.

**Comment by ChroustJan** [comment]
Bude zvýšen proud LED na 24mA. R4 ze 180R bude 51R.

**Comment by kaklik** [comment]
Ještě mne napadla jedna možnost, jak to zlepšit - snížit tloušťku víčka. Nyní je konec šroubu při dotažení utopený o 1,45mm pod povrchem krabičky.  Je zde tak 1mm rezerva na přiblížení LED k samolepce. 

Úpravy geometrie krabičky ale pomohly poměrně výrazně. 

![image](https://user-images.githubusercontent.com/1194177/111874510-f8121880-8995-11eb-932b-8cda43f8a241.png)

Nebylo to ale focené za stejných světelných podmínek.

**Comment by roman-dvorak** [comment]
Dobře, snížím tloušťku víčka o 1mm (pokud tomu něco nebude vadit).

Na fotce z prvního komentáře jsem vůbec netušil, že ta dioda svítí. Nová fotka je už s úpravou, kdy do led teče vyšší proud?

Moc se mi nelíbí, jak to svítí i mimo kroužku. Navrhoval bych ho zase trochu zúžit a nechat kuželovitý.

Myslím, že tato úprava neblokuje focení aktuální verze.

**Comment by kaklik** [comment]
> Na fotce z prvního komentáře jsem vůbec netušil, že ta dioda svítí. Nová fotka je už s úpravou, kdy do led teče vyšší proud?
>

Ne, to je zatím se starým PCB TFRPM01B. Stejný proud, jako předchozí fotka. 
 
> Moc se mi nelíbí, jak to svítí i mimo kroužku. Navrhoval bych ho zase trochu zúžit a nechat kuželovitý.
> 

Ok, jak myslíš, mě tohle zrovna nijak nevadí.

**Comment by kaklik** [comment]
> Dobře, snížím tloušťku víčka o 1mm (pokud tomu něco nebude vadit).

Tohle je zřejmě vhodné udělat i kvůli montáži. Tu normální nerezovou matku se mi před chvílí pod tou samolepkou podařilo skřížit, což je docela nepříjemná situace.  Předpokládám, že nižší díra tomu alespoň trochu zabrání.

**Comment by roman-dvorak** [comment]
Víčko ztenčeno o 1 mm v #1519754

**Comment by kaklik** [comment]
Pro svítivost LED jsme udělali maximum. I snížení víčka znatelně pomohlo. Aktuální stav je použitelný. Pro ty, co vyžadují ještě větší svítivost jsem založil[ tenhle návod](https://github.com/ThunderFly-aerospace/TFRPM01/blob/TFRPM01C/doc/README.md). 

![image](https://user-images.githubusercontent.com/1194177/112467806-c9b28580-8d67-11eb-8e99-21d0bd60b738.png)
