### ISSUE TITLE
Precise positioning of the Pulse LED

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#21]
Při testování svítivosti LED #20  jsem přišel na to, že otvor v krabičce zřejmě není přesně na správném místě odpovídajícím otvoru v PCB pro LED. 
Tahle skutečnost, pokud se potvrdí, tak kromě krabičky ovlivňuje ještě i návrh samolepky #14.

**Comment by roman-dvorak** [comment]
Ano, vypadá to tak, že je LED skutečně posunutá. 

Takto vypadá posuv na PCB oproti šroubu. 
![Snímek z 2021-03-24 15-31-52](https://user-images.githubusercontent.com/5196729/112328198-64528c00-8cb6-11eb-8ff0-c4d17b16573f.png)

Na krabičce/samolepce je to oproti šroubu na druhé straně. (zjistím přesnou hodnotu) 


Tohle bych navrhoval vyřešit posunutím LED na PCB při další výrobě. V okolí LED je relativně místo a připadá mi to jako bezpečná úprava. (Pokud jsou aktuální samolepky vyhovující)

**Comment by kaklik** [comment]
Jo souhlasím..  jen tu prosím pak napiš, kam @ChroustJan  má tu LED posunout. Nebo případně, jestli je ten screenshot správně, tak to zřejmě jde rovnou udělat.

**Comment by roman-dvorak** [comment]
Ne! ještě to @ChroustJan  nedělej, pošlu přesné umístění.

**Comment by kaklik** [comment]
@roman-dvorak  Není náhodou možné, že puntík na samolepce je správně, ale je špatně díra v krabičce? 
Protože je mi podezřelé, že už se mi po několikáté podařilo tu samolepku vůči puntíku pro LED nalepit posunutou na stejnou stranu..

**Comment by roman-dvorak** [comment]
Na PCB byla LEDka posunutá na druhou stranu, než měla být. Byla posunuta o přesnou pozici, která vychází z openscadu, ale na druhou stranu. To vytvořilo posuv o více než půl milimetru oproti otvoru.  Kontroloval jsem, že to sedí s openscadem i se svg samolepky. 

Zároveň jsem tam změnil footprint pro LEDku z knihoven z Kicadu - mělo by to usnadnit osazování. 

![obrazek](https://user-images.githubusercontent.com/5196729/158796255-2415bb6a-77e2-4287-ad8e-200310a648ec.png)

Opraveno ve verzi D

**Comment by ChroustJan** [comment]
@roman-dvorak přijde mi, že naše LED do zvoleného pouzdra nepasuje :(
![image](https://user-images.githubusercontent.com/9783606/159270512-d8810d48-dd35-427d-89dd-6f6e55326388.png)

**Comment by ChroustJan** [comment]
Provedl jsem opravu pouzdra LED, ale bohužel jsem posunul pozici LED. Je potřeba ohlídat správnou pozici. @roman-dvorak není možný nějaký posun, když bude docházet k tisku nových samolepek a výrobě nové krabičky?

**Comment by kaklik** [comment]
Tohle je teď v jakém stavu? Je to v nové revizi D už vyřešené, nebo není?

**Comment by ChroustJan** [comment]
Pro verzi D jsem navrhl nové frézované pouzdro. Pozice jsou nové po dohodě s @roman-dvorak.

**Comment by roman-dvorak** [comment]
Jo, vzhledem k tomu, že tam ledky budou dvě, bude úprava v krabičce a
samolepce, tak tohle nemá smysl řešit.

Nové pozice jsou umístěny tak, že je lze snadno odměřit od středu šroubu.
