### ISSUE TITLE
Kolize R1 s hranou krabičky

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#23]
Díky změně rozložení součastek, rezistor R1 koliduje s podpěrou PCB v krabičče. 
Řešením zřejmě je podpěrnou část po stranách hřebínku J1 trochu zkrátit, aby na R1 vzniklo místo.

**Comment by roman-dvorak** [comment]
#1519754 kolizní hrana pousunuta směrem ven z krabičky o 2 mm

**Comment by kaklik** [comment]
Vyřešeno, PCB nyní do krabičky pasuje bez kolize s rezistorem.
