### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#24]
Chtěl jsem ověřit jak lze vytvořit výkres ve FreeCADu a při té příležitosti jsem zjistil, že v souboru [TFRPM01C.wrl](https://github.com/ThunderFly-aerospace/TFRPM01/blob/TFRPM01C/hw/sch_pcb/TFRPM01C.wrl) jsou špatná data.

![image](https://user-images.githubusercontent.com/1194177/112749269-881d1700-8fc1-11eb-861a-1c070baac39a.png)

**Comment by ChroustJan** [comment]
Nedalo by se tohle generovat nějak automaticky? Aktuálně jsem nějak rychle nepřišel nato, jak to vygenerovat nově.

**Comment by kaklik** [comment]
> Nedalo by se tohle generovat nějak automaticky? Aktuálně jsem nějak rychle nepřišel nato, jak to vygenerovat nově.

Je to jeden z formátů, který lze ručně exportovat z KiCAD PCB prohlížeče. Jestli to jde exportovat nějak automaticky je zřejmě spíše otázka na @roman-dvorak .

**Comment by roman-dvorak** [comment]
Do doby, kdy se používal starý formát, tak bych řekl docela jistě ano :) Ale teď na to neumím odpovědět. Je potřeba zjistit chyby, co tam aktuálně jsou. I tohle generování se nyní provádí nějak jinak.

**Comment by ChroustJan** [comment]
Tohle mi přijde vhodné generovat automaticky, protože na aktualizaci se dá snadno zapomenout. Dává mi dost zabrat udržet schéma aktuální.

**Comment by ChroustJan** [comment]
Vygenerování nového modelu:
![image](https://user-images.githubusercontent.com/9783606/130758878-9d379c77-22fa-43d4-8a5a-b462f3fa9dcd.png)
