### ISSUE TITLE
Header pinout in top silksceen layer

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFRPM01#26]
pinout hřebínku pro připojení sondy je jen z jedné strany PCB, pokud je namontovaný popiskem dolu (bez krabičky) tak není popisek čitelný. Při další vyrobě bych navrhoval přidat pinout do horní vrstvy silkscreenu (tam, kde jsou součástky)

**Comment by roman-dvorak** [comment]
Ve verzi D jsou popisky pinů přidány i pod hřebinek

![obrazek](https://user-images.githubusercontent.com/5196729/158798935-04f8ce63-1186-4f88-b5b4-b81a56b5ebcb.png)

**Comment by kaklik** [comment]
Myslím, že provedení popisů je v pořádku, takže se může zavřít.
