### ISSUE TITLE
Optical probe readout

### ISSUE THREAD

**Issue by laronll** [ThunderFly-aerospace/TFRPM01#27]
I would like to know if the optical probe needs to have any code change for it to work? Another question is that aiming the board perpendicular to a propeller with attached reflective material should make the sensor get readings? And if I am looking for RPM readings I should be looking for the frequency( or count, etc) that the code prints out?

Thank you in advance

**Comment by roman-dvorak** [comment]
Hi, I assume that you want to use it with autopilot with PX4 firmware? 

There should be nothing needed to modify. The SW should be ready for that measurement. A number of reflective marks (per 1 rotation) can be set through [PX4 parameters](http://docs.px4.io/master/en/advanced_config/parameter_reference.html#PCF8583_ADDR). The driver provides value as frequency (count of revolutions per second, in Hz). Frequency is logged by autopilot and forwarded through the MavLink network. 

![obrazek](https://user-images.githubusercontent.com/5196729/142761273-891727f9-ae0c-4a3d-8b87-7fb95b4fb5d5.png)

In addition to the sensor (frequency sensor) TFRPM01, we also have a probe [TFPROBE02](https://github.com/ThunderFly-aerospace/TFPROBE01) (on the picture) that contains the optical reflective sensor itself. The sensor used works at a small distance (units of mm) so I think it is better to measure the engine speed than the propeller. (The reflective material on the propeller can change the position of the center of gravity quite significantly.) Or create your custom probe that will detect reflections from the propeller at a bigger distance. The TFRPM on the input contains a pullup resistor and Schmitt trigger to shape input signal.

**Comment by roman-dvorak** [comment]
@laronll  Do you have any additional questions? Otherwise, I would close this issue.
