### ISSUE TITLE
Náhrada za SN74LVC1G14QDCKRQ1

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFRPM01#29]
Invertující schmidtův KO [SN74LVC1G14QDCKRQ1](https://cz.mouser.com/ProductDetail/Texas-Instruments/SN74LVC1G14QDCKRQ1?qs=yPJbmYg%2FhokGUE8uIzwD4w%3D%3D) není aktuálně dostupný. Existuje za něj náhrada [74LVC1G14QW5-7 ](https://cz.mouser.com/ProductDetail/Diodes-Incorporated/74LVC1G14QW5-7?qs=sGAEpiMZZMv4BkFy%252BbL2aGHGRMlgSMspdtK7aNA9BaA%3D)

**Comment by ChroustJan** [comment]
Obvod nemá správné pouzdro. Je potřeba nalézt jinou náhradu.

**Comment by kaklik** [comment]
Náhradou zřejmě je [74LVC1G14SE-7](https://www.tme.eu/cz/details/74lvc1g14se-7/hradla-invertory/diodes-incorporated/)
