### ISSUE TITLE
Velikost otvoru pro matku sroubu

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#3]
Sroub stahujici krabicku ma ve vicku sestihran pro zapusteni matice. Ten je ale moc maly a matice tam nejde vlozit.  
Ma o 0.6mm mensi prumer, nez by mela mit. 

Resenim zrejme je pouziti sroubu ze [standardni knihovny](https://github.com/ThunderFly-aerospace/Openscad_stdlib).

**Comment by kaklik** [comment]
Pokusil jsem se použít knihovnu bolts.scad od @JanKott  Ale potíž je, že knihovna neumožňuje získat parametry rozměrů šroubu. Tudíž nelze její použití realizovat žádným přímým způsobem, neboť rozměry modelu jsou navázány na rozměry šroubu.

**Comment by JanKott** [comment]
Upravim bolts knihovnu

**Comment by JanKott** [comment]
Nyní jsou k dispozici funkce bolt_diameter, head_height, head_diameter, nut_height, nut_diameter, nut_pocket. Argumentem je velikost.
