### ISSUE TITLE
doc/assets is not publicly available

### ISSUE THREAD

**Issue by evigdorchik** [ThunderFly-aerospace/TFRPM01#32]
https://github.com/ThunderFly-aerospace/TFassets/tree/0e880890673280038b7d0563b1c3fd30bcba1a64 is not publicly available so the sub-module fails to update and this leads to problems.

**Comment by kaklik** [comment]
> https://github.com/ThunderFly-aerospace/TFassets/tree/0e880890673280038b7d0563b1c3fd30bcba1a64 is not publicly available so the sub-module fails to update and this leads to problems.

Dear @evigdorchik ,

Thank you for your notice. We are aware of this restriction in the public access to our TFassets repository.

This restriction is set deliberately. Given the importance of ensuring the authenticity of our product, we have decided to hide some source data related to the marking of our original production. In this way, we want to guarantee that our products will be identified as original.

We apologize for any inconvenience this may cause you when working with our repository. If you have any further questions or need assistance, please do not hesitate to contact us.
