### ISSUE TITLE
Rezistory v pouzdru 603

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#4]
Rezitory R6, R8, R1 a R10. Případně také R7 a R5.  U kterých lze očekávat požadavky na změnu i po osazení modulu mají pouzdro 603. Které je citlivé na preciznost letování více než 805. 
Tato volba nedává smysl vzhledem k tomu, že v okolí těchto rezistorů je dostatek místa.

**Comment by ChroustJan** [comment]
Navrhuji R7 nahradit pájecí ploškou. Je otázka zda nenahradit R5 10kOhm také pájecí ploškou, která bude z výroby propojena. Zde vidím riziko, že si jí někdo přeruší a následně si nepropojí nic. R1 a R10 dát do pouzdra 0805, zde opravdu hrozí změna uživatelem. R6 nahradit pájecí ploškou z výroby propojenou, která půjde přerušit nožem. A R8 nahradit pájecí ploškou.

**Comment by kaklik** [comment]
Ok, přijde mi to jako rozumné řešení: 

![image](https://user-images.githubusercontent.com/1194177/108358286-d6830d00-71ee-11eb-9138-de9be1d082dc.png)

**Comment by kaklik** [comment]
Změna rezistoru R2 na pouzdo 805 má ještě jeden pozitivní přínos. 
A to ten že po vyřešení issue https://github.com/ThunderFly-aerospace/TFPROBE01/issues/5 na tomto rezitoru bude pravděpodobně trvale poněkud větší ztrátový výkon. Tím pádem je výhodné, že i rezistor má větší pouzdro.
