### ISSUE TITLE
Zvážit nastavení I2C adresy pomocí pájecích plošek

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFRPM01#5]
Momentálně je adresa na modulu vybrána osezením rezistoru na správnou pozici. Tohle řešení má ale podobný problém jako #4 Takže uvažuje relativně dobře vybavenou dílnu.
Domnívám se že na zákazníka je to zbytečně vysoký požadavek.

V případe přepínání adresy by možná bylo možné modul vylepšit použitím cínovací plošky.

**Comment by kaklik** [comment]
Vyřešeno v rámci issue #4 přidáním cínovací plošky JP1 s default nastavením A0 na GND. 

![image](https://user-images.githubusercontent.com/1194177/108358286-d6830d00-71ee-11eb-9138-de9be1d082dc.png)
