### ISSUE TITLE
Hall/Optical external sensor board

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#7]
Na základě některých [nových aplikací modulu](https://github.com/ThunderFly-aerospace/TF-G2/issues/64
) by zřejmě bylo vhodné vytvořit externí plošný spoj s magnetickým a optickým snímačem. 

Obdobně jako je: https://ozrobotics.com/shop/maleetronic-opb9000-reflective-optical-sensor/
https://www.pololu.com/product/2459
https://www.electronics-lab.com/project/reflectance-based-proximity-sensor-using-si1102/

### Reflexive sensor 

Od reflexivního snímače na plošném spoji potřebujeme, aby byl citlivý na otvory nebo prohlubně ve 3D vytištěném dílu. Kódovací kotouček by tak neměl vyžadovat žádnou dodatečnou povrchovou úpravu.

Alternativně by snímač měl být citlivý na kódovací pásky vytištěné na papír, nebo fólii. 

- [VCNT2020](https://www.vishay.com/optical-sensors/list/product-84285/)
- [OPTOI](https://optoi.com/en/products/components/reflective-sensors)
- [GP2S60](https://eu.mouser.com/datasheet/2/365/gp2s60_e-106.pdf)
- [QRE1113GR](https://eu.mouser.com/datasheet/2/308/QRE1113_D-1814544.pdf)
- [SFH 9206](https://eu.mouser.com/ProductDetail/OSRAM-Opto-Semiconductors/SFH-9206?qs=wWC4CIiyLaOQlR9G3WZMlg==)
- [GP2S700HCP](https://eu.mouser.com/datasheet/2/365/gp2s700hcp_e-800.pdf)
- [EE-SY199](https://eu.mouser.com/datasheet/2/307/EE-SY199-1189542.pdf)
- [OPB733TR](https://eu.mouser.com/datasheet/2/414/OPB733-1545423.pdf)
- [EE-SY1200](https://eu.mouser.com/datasheet/2/307/en-ee_sy1200-24835.pdf)
- [OPR5005](https://eu.mouser.com/datasheet/2/414/OPR5005-1530512.pdf)

#### S integrovaným zpracováním signálu

- [OPB9000](https://cz.mouser.com/ProductDetail/Optek-TT-Electronics/OPB9000?qs=Ok18xCFj7msWl1O2KsmQxQ%3D%3D)

Tenhle snímač vypadá dobře, ale zřejmě se musí alespoň trošku digitálně ovládat. Tím pádem není vhodný pro jednoduché čidlo. Možná by jej někdy v budoucnu bylo dobré využít pro něco jako TFRPM02. 

#### Provedení s vývody: 

- [OPB715](https://eu.mouser.com/datasheet/2/414/OPB715-716-717-718-1530362.pdf)
- [OPB760](https://eu.mouser.com/datasheet/2/414/OPB760thru763-770thru773-NandT-1545415.pdf)

#### Reflexive encoder

https://eu.mouser.com/datasheet/2/678/av02-2790en_ds_aedr-850x_2016-10-07-1828277.pdf
https://docs.broadcom.com/doc/AV02-0088EN

### Hall magnetic sensor 

Magnetický snímač musí být citlivý na magnety zalepené do snímacího kotoučku. Použití magnetického snímače předpokládáme v prostředí, kde hrozí znečištění, které by mohlo ohrozit funkci optického snímače.

- [SL353LT](https://cz.mouser.com/ProductDetail/Honeywell/SL353LT?qs=pB3G9VbQXIenMOyKzoQ33g%3D%3D) - asi není úplně vhodný, protože má push-pull výstup.  Tohle by ale možná šlo vyřešit přidáním tranzistoru

- [AH3572](https://cz.mouser.com/datasheet/2/115/AH3572-1483253.pdf) - má otevřený kolektor, je vhodný pro paralelní spojení s optickým sensorem. 

## Zapojení

Modul je potřeba zapojit tak, aby při sepnutí jednoho ze snímačů došlo ke změně polarity výstupního signálu.  Prakticky ale modul bude používán tak, že bude vždy fungovat jen jeden snímač.

**Comment by ChroustJan** [comment]
@kaklik neměli by to spíš být dva PCB? Očekávám, že se dopředu bude vědět technologie, která bude použita. Myslím si, že zde potřebujeme mít co nejmenší PCB.

**Comment by kaklik** [comment]
> @kaklik neměli by to spíš být dva PCB? Očekávám, že se dopředu bude vědět technologie, která bude použita. Myslím si, že zde potřebujeme mít co nejmenší PCB.

Je to zřejmě možnost.  Podstatné bude hlavně to, jakým způsebem ty PCB budou připevněné a zda budou záménné.

**Comment by kaklik** [comment]
Solved by https://github.com/ThunderFly-aerospace/TFPROBE01
