### ISSUE TITLE
Zlepšení čitelnosti popisků krabičky

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFRPM01#8]
Popisky na boku krabičky jsou téměř nečitelné. 
Navrhoval bych je udělat vystouplé místo zapuštěných.

**Comment by kaklik** [comment]
Zatím čitelnost popisků touto změnou nebyla moc zlepšena. Zvětšení vystoupení písma do boku ze stěny mělo důsledek, že je slicer ani nevyslicoval. 

je navíc problém s tisknutelností TF loga, které se v současné velikosti s tryskou 0.4 mm netiskne příliš kvalitně.

**Comment by kaklik** [comment]
Nakonec byly popisky z krabičky odebrány úplně.  Důvod je, že je zřejmě není možné kvalitně vytisknout a tím působí neseriózně. 
Další vhodnější řešení by zřejmě bylo použití samolepek.  V případě této konstrukce krabičky zřejmě jedna větší zakrývající šroub a celou vrchní stranu krabičky. 
Samolepka tak potřebuje mít zaoblené rohy se stejným rádiusem, jako má krabička.

**Comment by ChroustJan** [comment]
Pokud budeme mít správně dlouhý šroub, tak samolepka ze strany matice může být přes celou plochu. Vrchní by měla mít otvor pro šroub.

**Comment by kaklik** [comment]
Já do teď uvažoval o samolepce pouze z jedné strany a to ze strany víčka. Protože ta krabička je konstruovaná tak, že se buď na spodní  stranu přilepí suchý zip, kterým se nalepí někam na UAV.  A nebo se použije delší šroub, kterým se někam přišroubuje skrz víčko.  (To má ale komplikaci že vidím poměrně velký problém v tom dělat kulatou díru pro šroub do samolepky.)

**Comment by ChroustJan** [comment]
Tak já to bral tak, že ten suchý zip dáš přes tu samolepku a nebo i z druhé strany bude díra pro šroub. Doufám, že tu díru umí udělat ten tiskař. Mohl by jedině být problém, že nebudou umět tak malou. A pak nevím jak to bude s přesností lepení, ale asi by nevadilo mít větší díru v samolepce. Pokud bude samolepka z obou stran, tak to zmenší ten důraz na kvalitu 3D tisku a bude to podle mě celé vypadat lépe. O tomto by jsme se měli pobavit společně před začátkem návrhu samolepek.

**Comment by kaklik** [comment]
Problém s kvalitou potisků je pravděpodobně vyřešen návrhem samolepky. 

![image](https://user-images.githubusercontent.com/1194177/111034541-80347300-8416-11eb-9c76-da377be66d4e.png)

**Comment by ChroustJan** [comment]
Nápisy z tisknutelné krabičky odstraněny. Jejich funkci zastane samolepka.
